INSERT  INTO genre VALUES (0, 'Все книги');
INSERT  INTO genre  VALUES (1, 'Боевик');
INSERT  INTO genre  VALUES (2, 'Военный');
INSERT  INTO genre  VALUES (3, 'Исторический');
INSERT  INTO genre  VALUES (4, 'Приключения');
INSERT  INTO genre  VALUES (5, 'Юмор');
INSERT  INTO genre  VALUES (6, 'Фантастика');
INSERT  INTO genre  VALUES (7, 'Фентези');
INSERT  INTO genre  VALUES (8, 'Криминал');
INSERT  INTO genre  VALUES (9, 'Роман');
INSERT  INTO genre  VALUES (10, 'Мистика');
INSERT  INTO genre  VALUES (11, 'Ужасы');

INSERT  INTO author (full_name) VALUES ('Первый автор');
INSERT  INTO author (full_name) VALUES ('Второй автор');
INSERT  INTO author (full_name) VALUES ('Третий автор');
INSERT  INTO author (full_name) VALUES ('4й автор');
INSERT  INTO author (full_name) VALUES ('5й автор');
INSERT  INTO author (full_name) VALUES ('6й автор');
INSERT  INTO author (full_name) VALUES ('7й автор');
INSERT  INTO author (full_name) VALUES ('8й автор');
INSERT  INTO author (full_name) VALUES ('9й автор');
INSERT  INTO author (full_name) VALUES ('10й автор');

INSERT INTO book (name,description, price) VALUES ('Первая книга', 'Some information', 99.99);
INSERT INTO book (name,description, price) VALUES ('Вторая книга', 'Some information', 199.99);
INSERT INTO book (name,description, price) VALUES ('Белая книга', 'Some information', 89.99);
INSERT INTO book (name,description, price) VALUES ('Красная книга', 'Some information', 69.99);
INSERT INTO book (name,description, price) VALUES ('Черная книга', 'Some information', 100);
INSERT INTO book (name,description, price) VALUES ('Золотая книга', 'Some information', 109.99);
INSERT INTO book (name,description, price) VALUES ('Старая книга', 'Some information', 50.50);
INSERT INTO book (name,description, price) VALUES ('Новая книга', 'Some information', 121.21);
INSERT INTO book (name,description, price) VALUES ('Интересная книга', 'Some information', 121.21);
INSERT INTO book (name,description, price) VALUES ('Лучшая книга', 'Some information', 199.99);


INSERT  INTO book_genres VALUES (1, 3);
INSERT  INTO book_genres VALUES (1, 4);
INSERT  INTO book_genres VALUES (1, 2);
INSERT  INTO book_genres VALUES (2, 1);
INSERT  INTO book_genres VALUES (2, 8);
INSERT  INTO book_genres VALUES (3, 10);
INSERT  INTO book_genres VALUES (3, 11);
INSERT  INTO book_genres VALUES (4, 9);
INSERT  INTO book_genres VALUES (4, 5);
INSERT  INTO book_genres VALUES (5, 6);
INSERT  INTO book_genres VALUES (5, 7);
INSERT  INTO book_genres VALUES (6, 4);
INSERT  INTO book_genres VALUES (6, 5);
INSERT  INTO book_genres VALUES (7, 3);
INSERT  INTO book_genres VALUES (7, 9);
INSERT  INTO book_genres VALUES (8, 9);
INSERT  INTO book_genres VALUES (8, 10);
INSERT  INTO book_genres VALUES (8, 11);
INSERT  INTO book_genres VALUES (9, 4);
INSERT  INTO book_genres VALUES (9, 5);
INSERT  INTO book_genres VALUES (9, 6);
INSERT  INTO book_genres VALUES (10, 6);
INSERT  INTO book_genres VALUES (10, 4);
INSERT  INTO book_genres VALUES (10, 1);

INSERT INTO book_authors VALUES (1, 1);
INSERT INTO book_authors VALUES (1, 10);
INSERT INTO book_authors VALUES (1, 5);
INSERT INTO book_authors VALUES (1, 7);
INSERT INTO book_authors VALUES (2, 2);
INSERT INTO book_authors VALUES (2, 4);
INSERT INTO book_authors VALUES (3, 3);
INSERT INTO book_authors VALUES (3, 8);
INSERT INTO book_authors VALUES (4, 8);
INSERT INTO book_authors VALUES (4, 2);
INSERT INTO book_authors VALUES (4, 5);
INSERT INTO book_authors VALUES (5, 5);
INSERT INTO book_authors VALUES (6, 9);
INSERT INTO book_authors VALUES (6, 7);
INSERT INTO book_authors VALUES (7, 7);
INSERT INTO book_authors VALUES (8, 1);
INSERT INTO book_authors VALUES (8, 6);
INSERT INTO book_authors VALUES (9, 6);
INSERT INTO book_authors VALUES (10, 2);
INSERT INTO book_authors VALUES (10, 5);
INSERT INTO book_authors VALUES (10, 10);

